services:
  todo-db:
    image: mysql:latest # MySQLの最新イメージを使用
    environment:
      MYSQL_ROOT_PASSWORD: local_root_pass  # ルートユーザーのパスワード
      MYSQL_DATABASE: todo_app                 # 起動時に作られるDB名
      MYSQL_USER: local_user                # 任意のユーザー
      MYSQL_PASSWORD: local_password            # 上記ユーザーのパスワード
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - dev_db_data:/var/lib/mysql   # データ永続化するために必要。コンテナ内の/var/lib/mysqlがホスト内（Docker内）db_dataに保存される
      - ./dev_init:/docker-entrypoint-initdb.d # init/init.sql に任意の初期データを書いておくと、コンテナ起動時に自動で実行される

volumes:
  dev_db_data:

